add_newline = true

format = """
[$username]($username_style)\
[$hostname]($hostname_style) \
[$directory]($directory_style) \
$git_branch$git_status
$character
"""

[username]
show_always = true
style_user = "bold fg:45"
style_root = "bold fg:196"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold fg:141"
format = "[@$hostname]($style)"

[directory]
style = "bold fg:118"
format = "[$path]($style)"
truncation_length = 4
truncate_to_repo = true

[git_branch]
style = "bold fg:198"
format = " [git:$branch]($style)"

[git_status]
style = "fg:250"
format = " [$all_status$ahead_behind]($style)"

[character]
success_symbol = "[❯](bold fg:45) "
error_symbol = "[❯](bold fg:196) "
